import { invokeLLMSafe, AITimeoutError, AIRateLimitError } from "../../_core/llm-safe";
import { TRPCError } from "@trpc/server";
import * as db from "../../db";
import { logger } from "../../lib/logger";

/**
 * Process a user message through the AI Coach and return the response.
 * Saves both user and assistant messages to chat history.
 *
 * Uses invokeLLMSafe which adds:
 *   - 10s timeout (configurable via AI_TIMEOUT_MS env var)
 *   - 2 retries with exponential back-off on transient failures
 *   - Structured error types → clean tRPC errors for the client
 *
 * @param {number} userId - The ID of the user requesting AI coach help.
 * @param {string} message - The message written by the user.
 * @returns {Promise<string>} The response generated by the AI model.
 * @throws {TRPCError} When the AI service times out, rate limits, or fails unexpectedly.
 */
export async function chat(userId: number, message: string) {
  await db.saveChatMessage({ userId, role: "user", content: message });
  const history = await db.getChatHistory(userId, 20);
  const stats   = await db.getUserStats(userId);

  const systemPrompt = `You are ArmPro Coach, an expert AI armwrestling coach. You help athletes improve their armwrestling performance.

User stats: Level ${stats?.level || 1}, XP: ${stats?.xp || 0}, Total workouts: ${stats?.totalWorkouts || 0}, Current streak: ${stats?.streak || 0} days.

Be motivating, specific, and knowledgeable about armwrestling techniques (hook, toproll, press, etc.), training methods, injury prevention, and competition preparation. Keep responses concise but helpful. Respond in the same language the user writes in.`;

  const messages = [
    { role: "system" as const, content: systemPrompt },
    ...history.slice(-10).map(m => ({ role: m.role as "user" | "assistant", content: m.content })),
  ];

  let response;
  try {
    response = await invokeLLMSafe({ messages });
  } catch (err) {
    // Map structured AI errors → clean tRPC errors the client can display
    if (err instanceof AITimeoutError) {
      throw new TRPCError({
        code: "TIMEOUT",
        message: "El coach tardó demasiado en responder. Intenta de nuevo.",
      });
    }
    if (err instanceof AIRateLimitError) {
      throw new TRPCError({
        code: "TOO_MANY_REQUESTS",
        message: "Demasiadas solicitudes al coach. Espera un momento.",
      });
    }
    // Unexpected error — log and return a graceful message
    logger.error({ err }, "[AI Coach] Unexpected error");
    throw new TRPCError({
      code: "INTERNAL_SERVER_ERROR",
      message: "El coach no está disponible en este momento. Intenta más tarde.",
    });
  }

  const aiContent =
    typeof response.choices[0]?.message?.content === "string"
      ? response.choices[0].message.content
      : "Lo siento, no pude procesar tu mensaje. Inténtalo de nuevo.";

  await db.saveChatMessage({ userId, role: "assistant", content: aiContent });
  return aiContent;
}
